#!/usr/bin/env bash

apps=(
  ack
  brew-cask
  emacs
  fasd
  git
  git-extras
  git-flow
  gnupg
  httpie
  htop-osx
  hub
  markdown
  python
  rcm
  reattach-to-user-namespace
  ssh-copy-id
  tmux
  zsh
)
echo "installing apps..."
brew install  ${apps[@]}
